# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcandidate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QInputDialog, QLineEdit, QFileDialog

import mysql.connector
from mysql.connector import Error
import pyttsx3
engine = pyttsx3.init()
engine.setProperty("rate",125)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 30, 251, 51))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 150, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 200, 121, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 260, 141, 41))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 150, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 260, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(400, 201, 181, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ADD CANDIDATE"))
        self.label_2.setText(_translate("MainWindow", "CANDIDATE NAME"))
        self.label_3.setText(_translate("MainWindow", "CANDIATE PARTY"))
        self.label_4.setText(_translate("MainWindow", "SUBMIT"))
        self.pushButton.setText(_translate("MainWindow", "SUBMIT"))
        self.comboBox.setItemText(0, _translate("MainWindow", "BJP"))
        self.comboBox.setItemText(1, _translate("MainWindow", "CONGRESS"))
        self.comboBox.setItemText(2, _translate("MainWindow", "JDS"))
        self.comboBox.setItemText(3, _translate("MainWindow", "OTHERS"))
        self.pushButton.clicked.connect(self.savecandidate)

    def savecandidate(self):
        #filename = QFileDialog.getOpenFileName(None, "BROWSE FILE", "png files", "*.png")
        #path = filename[0]
        #print(path)
        name = self.lineEdit.text()
        print(name)
        party = self.comboBox.currentText()
        print(party)
        connection = mysql.connector.connect(host='localhost',
                                             database='fvoting',
                                             user='root',
                                             password='root')
        cursor = connection.cursor()
        cursor.execute("select * from candidates where party='{}'".format(party))
        res = cursor.fetchall()
        if res==[]:
            cursor.execute("insert into candidates(name,party,votes)values('{}','{}','{}')".format(name,party,0))
            connection.commit()
            connection.close()
            engine.say("candidate updated to the database")
            engine.runAndWait()
        else:
            engine.say(party+" candidate already exists")
            engine.runAndWait()
        
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
