# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voting.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import * 
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import * 
from PyQt5.QtCore import *
import mysql.connector
from mysql.connector import Error
import pyttsx3
engine = pyttsx3.init()
engine.setProperty("rate",125)

import recognition
class Ui_MainWindow(object):
    vtrid=""
    aid=""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 891, 41))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(350, 320, 200, 40))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 320, 111, 31))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 120, 211, 51))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 200, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 200, 111, 31))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 260, 211, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 260, 111, 31))
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 390, 211, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "welcome to the smart face recognition based voting system"))
        '''self.comboBox.setItemText(0, _translate("MainWindow", "bjp"))
        self.comboBox.setItemText(1, _translate("MainWindow", "congress"))
        self.comboBox.setItemText(2, _translate("MainWindow", "jds"))
        self.comboBox.setItemText(3, _translate("MainWindow", "others"))'''
        self.label_2.setText(_translate("MainWindow", "SELECT PARTY"))
        self.pushButton.setText(_translate("MainWindow", "CAPTURE FACE"))
        self.label_3.setText(_translate("MainWindow", "YOUR ADHAR ID"))
        self.label_4.setText(_translate("MainWindow", "YOUR VOTER  ID"))
        self.pushButton_2.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.pushButton.clicked.connect(self.captureface)
        self.pushButton_2.clicked.connect(self.confvote)
        self.setcandidates()

    def setcandidates(self):
        connection = mysql.connector.connect(host='localhost',
                                         database='fvoting',
                                         user='root',
                                         password='root')
        cursor = connection.cursor()
        cursor.execute("select * from candidates")
        res = cursor.fetchall()
        if res==[]:
                engine.say("Candidates not found")
                engine.runAndWait()
        else:
            name1=res[0][1]
            party1=res[0][2]
            name2=res[1][1]
            party2=res[1][2]
            name3=res[2][1]
            party3=res[2][2]
            name4=res[3][1]
            party4=res[3][2]
            bjp = QIcon('bjp.jpg')
            congress = QIcon('congress.jpg')
            jds = QIcon('jds.png')
            #others = QIcon('bjp.jpg') 
            self.comboBox.setItemText(0,name1+" - "+party1  )
            self.comboBox.setItemText(1, name2+" - "+party2 )
            self.comboBox.setItemText(2, name3+" - "+party3)
            self.comboBox.setItemText(3, name4+" - "+party4 )
            self.comboBox.setItemIcon(0, bjp)
            self.comboBox.setItemIcon(1, jds)
            self.comboBox.setItemIcon(2, congress)
            

    def captureface(self):
        connection = mysql.connector.connect(host='localhost',
                                         database='fvoting',
                                         user='root',
                                         password='root')
        cursor = connection.cursor()
        
        engine.say("hold down we will recognize ur face")
        engine.runAndWait()
        adharid=recognition.updatevote()
        print(adharid)
        if adharid=='not found':
            engine.say("could not identify face")
            engine.runAndWait()
        else:
            cursor.execute("select * from voter where adharid='{}' and status='{}'".format(adharid,"not voted"))
            res = cursor.fetchall()
            if res==[]:
                engine.say("Details not found or you have already voted")
                engine.runAndWait()
            else:
                self.vtrid=res[0][1]
                print(self.vtrid)
                self.aid = res[0][2]
                print(self.aid)
                self.lineEdit.setText(str(self.aid))
                self.lineEdit_2.setText(str(self.vtrid))

    def confvote(self):
        party = self.comboBox.currentText()
        connection = mysql.connector.connect(host='localhost',
                                         database='fvoting',
                                         user='root',
                                         password='root')
        cursor = connection.cursor()
        print(self.aid)
        cursor.execute("select * from candidates where party='{}'".format(party))
        res = cursor.fetchall()
        print(res)
        votes=res[0][3]
        print(votes)
        votes=int(votes)
        votes+=1
        print(votes)
        cursor.execute("update candidates set votes='{}' where party='{}'".format(votes,party))
        connection.commit()
        cursor.execute("update voter set status='{}' where adharid='{}'".format('voted',self.aid))
        connection.commit()
        connection.close()
        engine.say("Thank you. your vote has been succesfully submited")
        engine.runAndWait()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
