# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voting.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from mysql.connector import Error
import pyttsx3
engine = pyttsx3.init()
engine.setProperty("rate",125)

import recognition

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 791, 41))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(320, 250, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 250, 111, 31))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 80, 220, 55))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 180, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 180, 111, 31))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "welcome to the smart face recognition based voting system"))
        self.comboBox.setItemText(0, _translate("MainWindow", "BJP"))
        self.comboBox.setItemText(1, _translate("MainWindow", "CONGRESS"))
        self.comboBox.setItemText(2, _translate("MainWindow", "JDS"))
        self.comboBox.setItemText(3, _translate("MainWindow", "OTHERS"))
        self.label_2.setText(_translate("MainWindow", "SELECT PARTY"))
        self.pushButton.setText(_translate("MainWindow", "CAPTURE FACE"))
        self.label_3.setText(_translate("MainWindow", "YOUR ADHAR ID"))
        self.pushButton.clicked.connect(self.vote)

    def vote(self):
        #adharid = self.lineEdit.text()
        party = self.comboBox.currentText()
        '''if adharid=="":
            engine.say("please enter your adharid")
            engine.runAndWait()
        else:'''
        connection = mysql.connector.connect(host='localhost',
                                         database='fvoting',
                                         user='root',
                                         password='root')
        cursor = connection.cursor()
        
        engine.say("hold down we will recognize ur face")
        engine.runAndWait()
        adharid=recognition.updatevote()
        print(adharid)
        if adharid=='not found':
            engine.say("could not identify face")
            engine.runAndWait()
        else:
            cursor.execute("select * from voter where adharid='{}' and status='{}'".format(adharid,"not voted"))
            res = cursor.fetchall()
            if res==[]:
                engine.say("Details not found or you have already voted")
                engine.runAndWait()
            else:
                vtrid=res[0][1]
                print(vtrid)
                aid = res[0][2]
                print(aid)
                self.lineEdit.setText(str(aid))
    def submitvote(self):
        print("updating")
        cursor.execute("select * from candidates where party='{}'".format(party))
        res = cursor.fetchall()
        print(res)
        votes=res[0][3]
        print(votes)
        votes=int(votes)
        votes+=1
        print(votes)
        cursor.execute("update candidates set votes='{}' where party='{}'".format(votes,party))
        connection.commit()
        cursor.execute("update voter set status='{}' where adharid='{}'".format('voted',adharid))
        connection.commit()
        connection.close()
        engine.say("thank you. your vote has been succesfully submited")
        engine.runAndWait()
            
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
